name: CONFIRM THAT ğŸ¶ IS CUTE THAN ğŸ˜¼

on:
  push:
  pull_request:
    branches:
      - master

env:
  FACT: "ğŸ¶ IS CUTE THAN ğŸ˜¼"

jobs:

  assembly_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install NASM
      run: sudo apt install -y nasm
    - name: ASSEMBLY DOG
      run: diff <(echo $FACT) <(make -s -C src/assembly)

  c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: C DOG
      run: diff <(echo $FACT) <(make -s -C src/c)
