name: CONFIRM THAT ğŸ¶ IS CUTE THAN ğŸ˜¼

on:
  push:
  pull_request:
    branches:
      - master

env:
  FACT: "ğŸ¶ IS CUTE THAN ğŸ˜¼"

jobs:

  assembly_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install NASM
      run: sudo apt install -y nasm
    - name: ASSEMBLY DOG
      run: diff <(echo $FACT) <(make -s -C src/assembly)

  c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: C DOG
      run: diff <(echo $FACT) <(make -s -C src/c)

  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      run: make -C src/rust lint
    - name: Rust DOG
      run: diff <(echo $FACT) <(make -s -C src/rust)

  dog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      run: make -C src/dog lint
    - name: Rust DOG
      run: diff <(echo $FACT) <(make -s -C src/dog)

  kotlin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: cd src/kotlin && chmod +x gradlew
    - name: Kotlin DOG
      run: diff <(echo $FACT) <(make -s -C src/kotlin)
